version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    # You can also specify other tool versions:
    # nodejs: "16"
  jobs:
    build:
      html:
        - make singlehtml
        - mkdir -p $READTHEDOCS_OUTPUT/html
        - mv build/singlehtml $READTHEDOCS_OUTPUT/html

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: source/conf.py

formats:
  - pdf

# Dependencies required to build your docs
python:
   install:
   - requirements: requirements.txt